### ISSUE TITLE
Integration with K8S

### ISSUE THREAD

**Issue by yingfeng** [uber/peloton#1]
Within your slide on [Kubcon 2018](https://sched.co/GrTx) there's an image on how to integrate Peloton with K8S---Kubernetize Peloton
![peloton](https://user-images.githubusercontent.com/7248/54098959-e7ffef80-43f1-11e9-80de-83b56166f403.jpg)
Has such a feature been provided? I could not see corresponding codes within the repository. Thank you~

**Comment by yingfeng** [comment]
I saw the future plans that have been mentioned in the previous engineering blog could answer the above question. 

```
We are also planning to migrate Mesos workloads to Kubernetes using Peloton, which would help Peloton adoption in the major cloud services, as Kubernetes already enjoys extensive support in that realm. Peloton already shares many common design patterns with Kubernetes in its API, as well as ability to conform with higher scalability requirements. The current design of Peloton has very few dependencies on Mesos except for the Mesos agent, and Kubelet could work as an agent in Peloton. In this approach, we can model Peloton as a more scalable core implementation of Kubernetes:

    Provide a Kubernetes compatible API on top of Peloton’s core API.
    Add a new Peloton host manager implementation which supports Kubelets.
    Existing systems, such as Michelangelo, Uber’s machine learning platform, can still use the native Peloton core API.
```

Does there exist any more detailed roadmap for such plans? Thanks~

**Comment by bnitin** [comment]
We are working with K8s folks on what the exact integration would look like. No detailed specifics yet.

**Comment by talaniz** [comment]
Closing this for now. I will work with the team to setup some communication on our roadmap and forthcoming news.
