### ISSUE TITLE
minicluster work on docker version > 18, not on the old version.

### ISSUE THREAD

**Issue by iit2009060** [uber/peloton#2]
I tried setting up with docker version Version 17.09.1- but fall to one exception at the end
`requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
 `
When I tried with Docker version 18.09.3 it works.

**Comment by mincai** [comment]
We have other developers who are able to run minicluster locally with docker version 17.09.1-ce-mac42 (21090). Could you please try to re-install your docker daemon and see if it works ?

**Comment by iit2009060** [comment]
Reinstalling the docker with old version worked.

**Comment by iit2009060** [comment]
Hi, I still faced this issue when building . minicluster of peloton.  There is a github link which mention the root cause  of this issue.  It  is related to docker. A simple restart works for me.
https://github.com/docker/compose/issues/3927
