### ISSUE TITLE
use only part of this package

### ISSUE THREAD

**Issue by vtolstov** [uber/peloton#3]
Can you provide suggestion for me, if i need to to schedule tasks on nodes. ?
So i need to have only decision on which node i can run task with specific requirements.

**Comment by zhixinwen** [comment]
Could you clarify your use case?
Are you trying to run a task on a specific node?

**Comment by vtolstov** [comment]
yes i have task wich can be represented by some struct, each task have cpu, memory, disk values,
and each node can be represented by some struct, that have cpu, memory, disk, network... and i want to put task tightly on nodes.

**Comment by vtolstov** [comment]
i know about bin packaging, but i need to work with 3-4 dimensions and items can't be rotated.

**Comment by vtolstov** [comment]
gentle ping..

**Comment by zhixinwen** [comment]
This may help you https://github.com/uber/peloton/blob/master/example/testjob_host_affinity_constraint.yaml

The constraint part takes a label which would schedule the task onto the host specified only.

**Comment by talaniz** [comment]
@vtolstov Have you had a chance to review the doc? I'd be interested to know your thoughts. Please add any comments or questions.

**Comment by vtolstov** [comment]
doc? doc is about how to use peloton when it runs as server and you send to it some api reqs.
My goal is to use only scheduler system, that from 20 nodes can take optimal node for my task.
So i need api doc for https://godoc.org/github.com/uber/peloton

**Comment by amittbose** [comment]
https://peloton.readthedocs.io/en/latest/api-reference/

**Comment by vtolstov** [comment]
thanks, this is started info. but if i don't want to run fully baked peloton server, but want via go api pass to function job spec and nodes, after it run get node suitable to start.
